### ISSUE TITLE
TypeError: cannot read property 'use' of undefined: i18n.use(initReacti18next).init line of i18n.js

### ISSUE THREAD

**Issue by sraisty1c** [i18next/react-i18next-gitbook#63] opened 2019-10-28 17:56 UTC
I've encountered problems difficulty upgrading our React-Typescript project from using i18next v17.1.0 and react-i18next 10.13.1 to current versions (i18next v17.3.1 & react-i18next v10.13.2).
Everything worked before with the older versions, but I can't seem to get rid of type error occurring in my i18n.ts file.  

The error is: "Uncaught TypeError: i18n.use is not a function at Object../src/app/i18n.ts (i18n.ts:9)"

Depending on how I import i18next into my i18n.ts file, either:
1) the web app fails in the browser with this Type Error,  but my jest/enzyme integration tests pass, 
OR 
2) the web app works fine (no error) but all my jest/enzyme tests fail with the aforementioned type error.

Things I've tried:

1) If I do the following in my i18n.js, then the tests pass but the web app fails in the browser:
```
import * as i18n from 'i18next';
```

2) If I do this instead, then the web app works, but tests fail:
```
import i18n from 'i18next';
```

3) If I do this (which I saw suggested in [this thread](https://github.com/i18next/i18next/issues/1177)), it fails in the browser but tests pass:
```
import * as i18nextDefault from 'i18next'
const i18n: typeof i18nextDefault = require('i18next');
```

4)  Setting tconfig's 'esModuleInterop' to TRUE works:  the web app works AND the tests all pass, but unfortunately I cannot use this project-wide setting because it causes dozens of other libraries used by our project to fail. 

I have a sample repo that reproduces the problem here:

Please see the minimal sample repo at https://github.com/sraisty1c/test-i18next 
You can look at the last 3 or 4 commits and see what I mean.

---
I'm sure this is some kind of user error, since I am pretty new to Typescript, React, and Javascript.  But I've been researching this for a day or two now, and feel like I'm at a dead end. I sincerely appreciate your help.  

And I thank you for putting out such a useful package. It has worked well for us for the last 8 months, which is why I want to figure out this problem so we can keep using it.

Thank you in advance for your help.

**Comment by jamuhl** [comment] 2019-10-28 18:06
@rosskevin...sorry to bother you again...need your help with this as the only recommendation I would able to make is get ride of typescript and embrace javascript as a type free language - but guess that's not what users coming from typed languages like to hear ;)

**Comment by rosskevin** [comment] 2019-10-28 19:50
non-esmoduleinterop working PR https://github.com/sraisty1c/test-i18next/pull/1

I'm going to do one with esmoduleinterop as well and retain it as a sample.

**Comment by rosskevin** [comment] 2019-10-28 19:56
Sorry, spoke to soon, that PR 1 isn't working.  I got the esModuleInterop working and noticed the different content.  Give me a bit to iron that out.

**Comment by rosskevin** [comment] 2019-10-28 20:19
Ok, so interestingly, it appears that using `tsc` to transpile `import * as` turns into `const i18n = require("i18next")`, which will (afaik) work.  I changed the sample to use webpack+babel only, no tsc/ts-loader.  

More detail: it sort of makes sense that babel doesn't know how to deal with `import * as`, but tsc does.  I'll try modifying the loaders again to see if I can get this combo working.

**Comment by jamuhl** [comment] 2019-10-28 20:25
@rosskevin my comment was not about the typings provided in i18next - like I always stated - I appreciate your work and quality on it. My opinion is about typescript in general...but an example in the react-i18next repo using typescript might be a good idea to reduce the amount of questions in future (good idea you had 👍)

**Comment by rosskevin** [comment] 2019-10-28 21:01
I'm going to log my findings as I go, because this is a set of experiments that are narrowing this down.  

This entire problem is due a combination of modules, loaders and tech and an explicit attempt to NOT use a setting in `tsc` that is intended FOR solving this exact problem. 

1.  `esModuleInterop: true` with `import i18n from 'ii18next'` via `tsc` generates:

```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const i18next_1 = __importDefault(require("i18next"));
i18next_1.default.use(react_i18next_1.initReactI18next).init({
```

2. `esModuleInterop: false` with `import * as i18n from 'ii18next'` via `tsc` generates:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var i18n = require("i18next");
i18n.use(react_i18next_1.initReactI18next).init({
```

Notes on `esModuleInterop: false`:
-`allowSyntheticDefaultImports` has no bearing on the output of non-interop.
- `import i18n = require('i18next')` is the same output as 2 above.
- `import i18n = require('i18next')` does not work because it is by default using the `esm` package, if it were to use the `cjs` package (as is loaded by jest/node), then this syntax would work.

From these notes, one might conclude (not tested yet) that if we forced usage of `cjs` instead of `esm`, then `import * as` would work like `import i18n = require('i18next')`.  I believe our babel loader settings are resolving i18next to esm via the current `@babel/preset-env` settings.  I will experiment there and see what happens.

**Comment by rosskevin** [comment] 2019-10-28 21:12
@jamuhl I believe you have a misunderstanding as to the cause of the problem, it is a standards problem not a typescript problem.  You just are not seeing it because you are used to the js echosystem which glosses over and by default provides interop with old commonjs style default exports.

`import * as` and `import` `default` are ecmascript standards.  TS (without `esModuleInterop: true`) is actually exposing the inaccuracies of the imports/exports.  So `esModuleInterop: true` makes it behave like typical js imports while `esModuleInterop: false` makes it break.

`esModuleInterop: false` is likely ahead of it's time it seems to me since so many developers are expecting a variety of imports to work.  If I'm wrong on any of the above, someone please feel free to correct me.

BTW - this is a reminder @jamuhl - if you get rid of `export default` all of these problems go away both now and forever in the future.  Named imports are good, simple, and just work, both for old commonjs modules, umd modules and esm modules, regardless of using strict or non-strict settings.

**Comment by rosskevin** [comment] 2019-10-28 21:25
Identical webpack issue that is not typescript related: https://github.com/webpack/webpack/issues/5756

**Comment by rosskevin** [comment] 2019-10-28 22:33
@sraisty1c I have PR'd a working non-esmoduleinterop to your repo.

Full explanation here with working example of `esModuleInterop: false` (NOT RECOMMENDED):
https://github.com/rosskevin/test-i18next/tree/non-esmoduleinterop-ts-loader

Companion branch of recommended `esModuleInterop: true`.
https://github.com/rosskevin/test-i18next/tree/esmoduleinterop

I want to be clear: this is not a _typescript problem_, it is one that _typescript exposes_.  Webpack insists on specific loader semantics, nodejs is stuck in commonjs loading semantics, libraries offer various bundles for consumer optimization (commonjs, esm), and test tools have a different runtime than web browsers.

`esModuleInterop: false` says:
> I know what I am doing, I care about the differences and I want it to break.

This IS NOT what userland typically wants.  If you are not an expert user that wants to master the module types differences in imports and manipulation of module loading for jest and webpack, then DO NOT use this setting.  If you want it to just work, typescript is quite awesome, it covers all of these differences noted above with a simple `esModuleInterop: true`.

---

@jamuhl this issue can be closed.  Please review my writeup and let me know if you have questions.

**Comment by jamuhl** [comment] 2019-10-29 07:49
Changing to named export would only make sense if we change to exporting functions

`import { t, changeLanguage } from 'i18next'` instead of the "class"... 

So it looks like typescript decided to use `esModuleInterop: false` as default while webpack decided on using `esModuleInterop: true`

**Closed by jamuhl** 2019-10-29 07:49 UTC

**Comment by Vanuan** [comment] 2019-12-22 21:35
I'm afraid this issue has nothing to do with exported modules and has everything to do with example of jest-mocking introduced in #42
